CREATE TABLE IF NOT EXISTS Book (
BookCode INTEGER UNIQUE NOT NULL PRIMARY KEY AUTOINCREMENT,
Title TEXT,
Author TEXT,
Publisher TEXT,
Subject TEXT,
Type INTEGER,
Date TEXT,
Language TEXT,
FileName TEXT,
Position REAL DEFAULT 0,
IsFixedLayout INTEGER DEFAULT 0,
IsGlobalPagination INTEGER DEFAULT 0,
IsDownloaded INTEGER DEFAULT 0,
FileSize INTEGER DEFAULT -1,
CustomOrder INTEGER DEFAULT 0,
URL	TEXT,
CoverURL TEXT,
DownSize INTEGER DEFAULT -1,
IsRead INTEGER DEFAULT 0,
LastRead Text,
IsRTL INTEGER DEFAULT 0,
IsVerticalWriting INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Highlight (
BookCode INTEGER NOT NULL,
Code INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
ChapterIndex INTEGER,
StartIndex INTEGER,
StartOffset INTEGER,
EndIndex INTEGER,
EndOffset INTEGER,
Color INTEGER,
Text TEXT,
Note TEXT,
IsNote INTEGER DEFAULT 0,
CreatedDate TEXT
);

CREATE TABLE IF NOT EXISTS Paging (
BookCode INTEGER NOT NULL,
Code INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
ChapterIndex INTEGER,
NumberOfPagesInChapter INTEGER,
FontName TEXT,
FontSize INTEGER,
LineSpacing INTEGER,
Width INTEGER,
Height INTEGER,
VerticalGapRatio REAL,
HorizontalGapRatio REAL,
IsPortrait INTEGER,
IsDoublePagedForLandscape INTEGER
);

CREATE TABLE IF NOT EXISTS Bookmark (
BookCode INTEGER NOT NULL,
Code INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
ChapterIndex INTEGER,
PagePositionInChapter REAL,
PagePositionInBook REAL,
Description TEXT,
CreatedDate TEXT
);

CREATE TABLE IF NOT EXISTS Setting (
BookCode INTEGER NOT NULL,
FontName TEXT         "TimesRoman",
FontSize INTEGER      DEFAULT  3,
LineSpacing INTEGER   DEFAULT -1,
Foreground INTEGER    DEFAULT -1,
Background INTEGER    DEFAULT -1,
Theme INTEGER         DEFAULT  0,
Brightness REAL       DEFAULT  0,
TransitionType INTEGER DEFAULT 2,
LockRotation INTEGER DEFAULT 0,
DoublePaged  INTEGER DEFAULT 1,
Allow3G		 INTEGER DEFAULT 1,
GlobalPagination INTEGER DEFAULT 0
);


